### ISSUE TITLE
Not Connected!

### ISSUE THREAD

**Issue by AminEshtiaghi** [fiorix/sms-api-server#2]
Hello, I'm using sms-api-server docker, the index page is resolving + the status of page is connected, but when I've called the v1/send or v1/query, it  returns the message of "not connected".

I've tried  it multiple times.

coudl you help me to find the issue.

Note:
I'm using docker compose:

sms:
    image: fiorix/sms-api-server
    container_name: "docker-sms"
    ports:
      - "9881:8080"
    networks:
      - docker-network

**Comment by fiorix** [comment]
Closing as stale (filed 2020, no follow-up).

For anyone hitting the same: "not connected" means the server isn't bound to an SMSC. The HTTP UI reports the HTTP status, not the SMPP link. Required config:

- `-smpp host:port` — SMSC address (no default)
- `SMPP_USER` / `SMPP_PASSWD` env vars — bind credentials

Example:
```yaml
sms:
  image: fiorix/sms-api-server
  command: ["-smpp", "smsc.example.com:2775"]
  environment:
    SMPP_USER: youruser
    SMPP_PASSWD: yourpass
  ports: ["9881:8080"]
```

If you reproduce on current master with valid SMSC creds and still see "not connected", please open a new issue with logs.
